# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 7bf478c0f47e7ab3b9ecfdcfb26bdb65f2c712ccd49bc5949d1cc5b42993083a87f8b246c2e608fc5eb86a4978328e55655e2078a4360729c40585d008d80e96

test:
  secret_key_base: a225ec4f3e89925a383b84833ac42fc32f3da2897e9a203b16e7bb4d1c5a66e68797d4e50ad6dbd8ad79da9196102c9ca81c89ea8c47a9a82712622f3af31f89

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
